services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: fooduser
      POSTGRES_PASSWORD: foodpass
      POSTGRES_DB: foodrecipes
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v2.40.0
    restart: always
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://fooduser:foodpass@postgres:5432/foodrecipes
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET:      myhasurasecret
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "public"
    depends_on:
      - postgres

volumes:
  postgres_data:
